server:
  port: 10086 #server port
spring:
  application:
    name: eurakaserver # the name of eureka server
eureka:
  client:
    service-url:  # eureka info of address
      defaultZone: http://127.0.0.1:10086/eureka